from django.urls import path

from analytics.views import (
    AnalyticsCommandCenterView,
    AssessmentEventDetailView,
    AssessmentEventListView,
    AssessmentImportConfirmView,
    AssessmentImportDetailView,
    AssessmentImportListView,
    AssessmentImportPreviewView,
    AssessmentImportResolveView,
    AssessmentImportUploadView,
    CoachAssessmentDetailView,
    CoachAssessmentEditView,
    CoachAssessmentListView,
    EvaluationListView,
    EvaluationPlayerView,
    EvaluationReviewDetailView,
    EvaluationReviewListView,
    MyEvaluationDetailView,
    MyEvaluationsPlayerView,
    MyEvaluationsView,
    PlayerComparisonView,
    PlayerProfileView,
    PlayerImportConfirmView,
    PlayerImportConflictView,
    PlayerImportDetailView,
    PlayerImportListView,
    PlayerImportPreviewView,
    PlayerImportUploadView,
    PlayerAssessmentDetailView,
    PlayerSearchView,
    StaffObservationReviewDetailView,
    StaffObservationReviewListView,
)


app_name = "analytics"

urlpatterns = [
    path("", AnalyticsCommandCenterView.as_view(), name="command-center"),
    path("players/", PlayerSearchView.as_view(), name="player-search"),
    path("players/compare/", PlayerComparisonView.as_view(), name="player-compare"),
    path("players/<int:player_id>/", PlayerProfileView.as_view(), name="player-profile"),
    path("assessment-events/", AssessmentEventListView.as_view(), name="assessment-event-list"),
    path("assessment-events/<int:event_id>/", AssessmentEventDetailView.as_view(), name="assessment-event-detail"),
    path("player-assessments/<int:pk>/", PlayerAssessmentDetailView.as_view(), name="player-assessment-detail"),
    path("assessment-imports/", AssessmentImportListView.as_view(), name="assessment-import-list"),
    path("assessment-imports/new/", AssessmentImportUploadView.as_view(), name="assessment-import-new"),
    path("assessment-imports/<int:pk>/preview/", AssessmentImportPreviewView.as_view(), name="assessment-import-preview"),
    path("assessment-imports/<int:pk>/resolve/", AssessmentImportResolveView.as_view(), name="assessment-import-resolve"),
    path("assessment-imports/<int:pk>/confirm/", AssessmentImportConfirmView.as_view(), name="assessment-import-confirm"),
    path("assessment-imports/<int:pk>/", AssessmentImportDetailView.as_view(), name="assessment-import-detail"),
    path("evaluations/", EvaluationListView.as_view(), name="evaluation-list"),
    path("evaluations/players/<int:player_id>/", EvaluationPlayerView.as_view(), name="evaluation-player"),
    path("evaluation-review/", EvaluationReviewListView.as_view(), name="evaluation-review-list"),
    path("evaluation-review/<int:observation_id>/", EvaluationReviewDetailView.as_view(), name="evaluation-review-detail"),
    path("my/evaluations/", MyEvaluationsView.as_view(), name="my-evaluations"),
    path("my/evaluations/players/<int:player_id>/", MyEvaluationsPlayerView.as_view(), name="my-evaluations-player"),
    path("my/evaluations/<int:observation_id>/", MyEvaluationDetailView.as_view(), name="my-evaluation-detail"),
    path("assessments/", CoachAssessmentListView.as_view(), name="assessment-list"),
    path("assessments/players/<int:player_id>/", CoachAssessmentEditView.as_view(), name="assessment-player"),
    path("assessments/<int:observation_id>/", CoachAssessmentDetailView.as_view(), name="assessment-detail"),
    path("assessments/<int:observation_id>/edit/", CoachAssessmentEditView.as_view(), name="assessment-edit"),
    path("observations/review/", StaffObservationReviewListView.as_view(), name="observation-review-list"),
    path("observations/<int:observation_id>/review/", StaffObservationReviewDetailView.as_view(), name="observation-review-detail"),
    path("imports/", PlayerImportListView.as_view(), name="import-list"),
    path("imports/new/", PlayerImportUploadView.as_view(), name="import-new"),
    path("imports/<int:pk>/preview/", PlayerImportPreviewView.as_view(), name="import-preview"),
    path("imports/<int:pk>/conflicts/", PlayerImportConflictView.as_view(), name="import-conflicts"),
    path("imports/<int:pk>/confirm/", PlayerImportConfirmView.as_view(), name="import-confirm"),
    path("imports/<int:pk>/", PlayerImportDetailView.as_view(), name="import-detail"),
]
