# Generated by Django 4.2.25 on 2026-05-01 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=220)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('awarded', 'Awarded'), ('not_selected', 'Not selected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('player_full_name', models.CharField(max_length=220)),
                ('date_of_birth', models.DateField()),
                ('vcb_team_or_program', models.CharField(max_length=180)),
                ('primary_positions', models.CharField(max_length=180)),
                ('years_participated_in_vcb_programs', models.CharField(max_length=120)),
                ('pathway_college_university', models.BooleanField(default=False)),
                ('pathway_trade_vocational_training', models.BooleanField(default=False)),
                ('pathway_recognized_training_program', models.BooleanField(default=False)),
                ('pathway_undecided', models.BooleanField(default=False)),
                ('institution_or_program_name', models.CharField(blank=True, max_length=220)),
                ('intended_field_of_study_or_training', models.CharField(blank=True, max_length=220)),
                ('nomination_statement', models.TextField()),
                ('confirm_information_is_accurate', models.BooleanField(default=False)),
                ('confirm_good_standing', models.BooleanField(default=False)),
                ('confirm_decisions_are_final', models.BooleanField(default=False)),
                ('consent_to_reference_checks', models.BooleanField(default=False)),
                ('nominator_signature', models.CharField(max_length=220)),
                ('signature_date', models.DateField()),
                ('transcript_or_report_card', models.FileField(blank=True, upload_to='scholarships/transcripts/')),
                ('supporting_documents', models.FileField(blank=True, upload_to='scholarships/supporting/')),
                ('internal_review_notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarshipapplicantprofile')),
            ],
            options={
                'ordering': ['-submitted_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('application_open_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('public_announcement', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', '-application_deadline'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('role_relationship', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='scholarships.scholarshipapplication')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarshipcycle'),
        ),
        migrations.AddConstraint(
            model_name='scholarshipapplication',
            constraint=models.UniqueConstraint(fields=('applicant', 'cycle'), name='unique_scholarship_application_per_cycle'),
        ),
    ]
