"""Public façade for the player import workflow.

Implementation lives in ``players.services.imports`` modules so callers can keep
using the stable import-service API while the internals stay easier to navigate.
"""

from players.services.imports.commit import (
    apply_player_updates,
    attach_source_identifiers,
    commit_import_batch,
    create_import_batch,
    create_player_from_import,
    record_import_source_row,
)
from players.services.imports.constants import (
    ACTION_CREATE,
    ACTION_ERROR,
    ACTION_NEEDS_REVIEW,
    ACTION_SKIP,
    ACTION_UPDATE,
    CONFLICT_FIELDS,
    HEADER_ALIASES,
    IDENTIFIER_FIELD_TYPES,
    MAPPING_KEY_ACTIVATE_PLAYER_ACCOUNTS,
    MAPPING_KEY_PROVISION_PLAYER_ACCOUNTS,
    MAX_CSV_ROWS,
    MAX_CSV_UPLOAD_BYTES,
    PERMANENT_PLAYER_FIELD_KEYS,
    PLAYER_FIELD_KEYS,
    RESOLUTION_ACTION_COMMIT,
    RESOLUTION_ACTION_CREATE_NEW,
    RESOLUTION_ACTION_USE_CANDIDATE,
    RESOLUTION_KEEP_EXISTING,
    RESOLUTION_METADATA_ONLY,
    RESOLUTION_USE_IMPORTED,
    SOURCE_CHOICES,
    SOURCE_MANUAL_STAFF,
    SOURCE_MEMBER_LIST,
    SOURCE_ROSTER_DETAIL,
)
from players.services.imports.mapping import (
    build_identity_payload,
    build_roster_payload,
    build_source_identifiers,
)
from players.services.imports.parsing import (
    ROSTER_STATUS_ALIASES,
    build_column_choices,
    clean_cell,
    deserialize_preview,
    detect_source_from_filename,
    normalize_header,
)
from players.services.imports.parsing import normalize_source as _normalize_source
from players.services.imports.parsing import (
    parse_birth_year,
    parse_birthdate,
    parse_import_date,
    parse_player_csv,
    parse_roster_status,
    serialize_preview,
    split_full_name,
    suggest_mapping,
)
from players.services.imports.preview import (
    build_import_preview,
    current_preview,
    preview_row,
)
from players.services.imports.result_models import (
    FieldConflict,
    ImportCommitResult,
    ImportIdentityRow,
    ImportPreviewRow,
    ImportRowResult,
    ParsedCsvFile,
)

__all__ = [
    "ACTION_CREATE",
    "ACTION_ERROR",
    "ACTION_NEEDS_REVIEW",
    "ACTION_SKIP",
    "ACTION_UPDATE",
    "CONFLICT_FIELDS",
    "FieldConflict",
    "HEADER_ALIASES",
    "IDENTIFIER_FIELD_TYPES",
    "ImportCommitResult",
    "ImportIdentityRow",
    "ImportPreviewRow",
    "ImportRowResult",
    "MAPPING_KEY_ACTIVATE_PLAYER_ACCOUNTS",
    "MAPPING_KEY_PROVISION_PLAYER_ACCOUNTS",
    "MAX_CSV_ROWS",
    "MAX_CSV_UPLOAD_BYTES",
    "PERMANENT_PLAYER_FIELD_KEYS",
    "PLAYER_FIELD_KEYS",
    "ParsedCsvFile",
    "RESOLUTION_ACTION_COMMIT",
    "RESOLUTION_ACTION_CREATE_NEW",
    "RESOLUTION_ACTION_USE_CANDIDATE",
    "RESOLUTION_KEEP_EXISTING",
    "RESOLUTION_METADATA_ONLY",
    "RESOLUTION_USE_IMPORTED",
    "ROSTER_STATUS_ALIASES",
    "SOURCE_CHOICES",
    "SOURCE_MANUAL_STAFF",
    "SOURCE_MEMBER_LIST",
    "SOURCE_ROSTER_DETAIL",
    "_normalize_source",
    "apply_player_updates",
    "attach_source_identifiers",
    "build_column_choices",
    "build_identity_payload",
    "build_import_preview",
    "build_roster_payload",
    "build_source_identifiers",
    "clean_cell",
    "commit_import_batch",
    "create_import_batch",
    "create_player_from_import",
    "current_preview",
    "deserialize_preview",
    "detect_source_from_filename",
    "normalize_header",
    "parse_birth_year",
    "parse_birthdate",
    "parse_import_date",
    "parse_player_csv",
    "parse_roster_status",
    "preview_row",
    "record_import_source_row",
    "serialize_preview",
    "split_full_name",
    "suggest_mapping",
]
