# Generated by Django 4.2.25 on 2026-07-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_playerimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('cycle_type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-starts_on', '-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation_type_key', models.CharField(editable=False, max_length=80)),
                ('evaluator_role_key', models.CharField(blank=True, max_length=80)),
                ('evaluator_role_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reopened', 'Reopened'), ('archived', 'Archived')], default='draft', max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evaluation_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='analytics.evaluationcycle')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_observations', to=settings.AUTH_USER_MODEL)),
                ('evaluator_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='analytics.evaluatorrole')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ObservationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('prompt', models.CharField(max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('response_type', models.CharField(choices=[('rating_1_5', '1-5 Rating'), ('text', 'Text'), ('boolean', 'Boolean'), ('multiple_choice', 'Multiple Choice'), ('velocity', 'Velocity'), ('time', 'Time'), ('distance', 'Distance')], max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('min_numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['question_set', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObservationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['is_active', 'key'], name='analytics_o_is_acti_b20ba2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObservationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['is_active', 'key'], name='analytics_o_is_acti_8d2891_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObservationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_type', models.CharField(choices=[('rating_1_5', '1-5 Rating'), ('text', 'Text'), ('boolean', 'Boolean'), ('multiple_choice', 'Multiple Choice'), ('velocity', 'Velocity'), ('time', 'Time'), ('distance', 'Distance')], max_length=40)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('selected_choice', models.CharField(blank=True, max_length=120)),
                ('raw_value', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='analytics.observation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='analytics.observationquestion')),
            ],
            options={
                'ordering': ['question__display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObservationQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('retired_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('observation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_sets', to='analytics.observationtype')),
            ],
            options={
                'ordering': ['observation_type__key', '-version'],
            },
        ),
        migrations.AddField(
            model_name='observationquestion',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='analytics.observationquestionset'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='analytics.observationtype'),
        ),
        migrations.AddField(
            model_name='observation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='players.player'),
        ),
        migrations.AddField(
            model_name='observation',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='analytics.observationquestionset'),
        ),
        migrations.AddField(
            model_name='observation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='analytics.observationsource'),
        ),
        migrations.AddIndex(
            model_name='evaluatorrole',
            index=models.Index(fields=['is_active', 'key'], name='analytics_e_is_acti_f01705_idx'),
        ),
        migrations.AddField(
            model_name='evaluationcycle',
            name='coach_assessment_question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_cycles', to='analytics.observationquestionset'),
        ),
        migrations.AddIndex(
            model_name='observationresponse',
            index=models.Index(fields=['observation', 'question'], name='analytics_o_observa_2faaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='observationresponse',
            index=models.Index(fields=['question', 'numeric_value'], name='analytics_o_questio_12550a_idx'),
        ),
        migrations.AddIndex(
            model_name='observationresponse',
            index=models.Index(fields=['response_type'], name='analytics_o_respons_3ab3fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationresponse',
            constraint=models.UniqueConstraint(fields=('observation', 'question'), name='analytics_unique_response_per_question'),
        ),
        migrations.AddIndex(
            model_name='observationquestionset',
            index=models.Index(fields=['observation_type', 'is_active'], name='analytics_o_observa_aaeb63_idx'),
        ),
        migrations.AddIndex(
            model_name='observationquestionset',
            index=models.Index(fields=['observation_type', 'version'], name='analytics_o_observa_7302c7_idx'),
        ),
        migrations.AddIndex(
            model_name='observationquestionset',
            index=models.Index(fields=['effective_from', 'retired_on'], name='analytics_o_effecti_4e4c7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationquestionset',
            constraint=models.UniqueConstraint(fields=('observation_type', 'version'), name='analytics_unique_question_set_version'),
        ),
        migrations.AddIndex(
            model_name='observationquestion',
            index=models.Index(fields=['question_set', 'display_order'], name='analytics_o_questio_c74efc_idx'),
        ),
        migrations.AddIndex(
            model_name='observationquestion',
            index=models.Index(fields=['question_set', 'is_active'], name='analytics_o_questio_b9faac_idx'),
        ),
        migrations.AddIndex(
            model_name='observationquestion',
            index=models.Index(fields=['category', 'display_order'], name='analytics_o_categor_6d42a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationquestion',
            constraint=models.UniqueConstraint(fields=('question_set', 'key'), name='analytics_unique_question_key_per_set'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['player', '-created_at'], name='analytics_o_player__8865bf_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['evaluation_cycle', 'observation_type', 'status'], name='analytics_o_evaluat_64d615_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['evaluator', 'evaluation_cycle'], name='analytics_o_evaluat_27a290_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['evaluator_role_key', 'evaluation_cycle'], name='analytics_o_evaluat_4581bb_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['observation_type_key', 'status'], name='analytics_o_observa_1d6714_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['submitted_at'], name='analytics_o_submitt_d5caa4_idx'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluator__isnull', False), ('observation_type_key', 'coach_assessment')), fields=('player', 'evaluation_cycle', 'observation_type_key', 'evaluator'), name='analytics_unique_coach_assessment_per_evaluator'),
        ),
        migrations.AddIndex(
            model_name='evaluationcycle',
            index=models.Index(fields=['is_active', 'starts_on'], name='analytics_e_is_acti_211b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcycle',
            index=models.Index(fields=['cycle_type', 'is_active'], name='analytics_e_cycle_t_be9b44_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcycle',
            index=models.Index(fields=['slug'], name='analytics_e_slug_2c6d38_idx'),
        ),
    ]
