# Generated by Django 4.2.25 on 2026-07-11 06:26

from django.db import migrations, models


def backfill_evaluation_perspective(apps, schema_editor):
    Observation = apps.get_model("analytics", "Observation")
    role_mapping = {
        "player": "peer",
        "coach": "coach",
        "assistant_coach": "coach",
        "head_coach": "coach",
        "coordinator": "coach",
        "staff": "staff",
        "admin": "staff",
        "guest_evaluator": "guest",
    }
    for role_key, perspective in role_mapping.items():
        Observation.objects.filter(evaluator_role_key=role_key).update(evaluation_perspective=perspective)


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_seed_observation_defaults'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='observation',
            name='analytics_unique_coach_assessment_per_evaluator',
        ),
        migrations.AddField(
            model_name='observation',
            name='evaluation_perspective',
            field=models.CharField(choices=[('self', 'Self Evaluation'), ('peer', 'Peer Evaluation'), ('coach', 'Coach Evaluation'), ('staff', 'Staff Evaluation'), ('guest', 'Guest Evaluation')], default='guest', max_length=40),
        ),
        migrations.RunPython(backfill_evaluation_perspective, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['evaluation_perspective', 'evaluation_cycle'], name='analytics_o_evaluat_b05f17_idx'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluator__isnull', False), ('observation_type_key', 'coach_assessment')), fields=('player', 'evaluation_cycle', 'observation_type_key', 'evaluator', 'evaluation_perspective'), name='analytics_unique_coach_assessment_per_perspective'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluation_perspective', 'self'), ('observation_type_key', 'coach_assessment')), fields=('player', 'evaluation_cycle', 'observation_type_key', 'evaluation_perspective'), name='analytics_unique_self_assessment_per_player'),
        ),
    ]
