# Generated by Django 4.2.25 on 2026-07-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('analytics', '0003_remove_observation_analytics_unique_coach_assessment_per_evaluator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcycle',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_cycles', to='seasons.season'),
        ),
        migrations.AddField(
            model_name='observation',
            name='evaluator_assignment_role_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='observation',
            name='evaluator_coach_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='seasons.coachseasonassignment'),
        ),
        migrations.AddField(
            model_name='observation',
            name='evaluator_division_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='observation',
            name='evaluator_team_name_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='observation',
            name='player_division_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='observation',
            name='player_roster_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='seasons.playerrostermembership'),
        ),
        migrations.AddField(
            model_name='observation',
            name='player_team_name_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='observation',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='seasons.season'),
        ),
        migrations.AddField(
            model_name='observation',
            name='season_key_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='observation',
            name='season_name_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddIndex(
            model_name='evaluationcycle',
            index=models.Index(fields=['season', 'is_active'], name='analytics_e_season__ed70e0_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['season', 'status'], name='analytics_o_season__b14210_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['season', 'player_roster_membership', 'status'], name='analytics_o_season__1bdeda_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['evaluator_coach_assignment', 'status'], name='analytics_o_evaluat_462a1b_idx'),
        ),
    ]
