# Generated by Django 4.2.30 on 2026-07-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_evaluationcycle_season_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observationquestion",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
