# Generated by Django 4.2.30 on 2026-07-31 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seasons', '0001_initial'),
        ('players', '0003_playerimportbatch_season_and_more'),
        ('analytics', '0005_alter_observationquestion_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('division', models.CharField(blank=True, max_length=80)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-starts_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('workbook_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('previewed', 'Previewed'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=40)),
                ('preview_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_key', models.CharField(max_length=180)),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_row', models.PositiveIntegerField()),
                ('raw_identity', models.CharField(blank=True, max_length=180)),
                ('action', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('ambiguous', 'Ambiguous'), ('invalid', 'Invalid'), ('skipped', 'Skipped'), ('committed', 'Committed')], default='unmatched', max_length=40)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('values_snapshot', models.JSONField(blank=True, default=list)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['batch', 'source_sheet', 'source_row', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('default_value_type', models.CharField(choices=[('number', 'Number'), ('rating', 'Rating'), ('text', 'Text'), ('choice', 'Choice')], default='number', max_length=40)),
                ('default_unit', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('retired_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplateMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('display_name', models.CharField(max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('value_type', models.CharField(choices=[('number', 'Number'), ('rating', 'Rating'), ('text', 'Text'), ('choice', 'Choice')], default='number', max_length=40)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('is_required', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rating_scale_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating_scale_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('direction', models.CharField(choices=[('higher', 'Higher is better'), ('lower', 'Lower is better'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('help_text', models.TextField(blank=True)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_metrics', to='analytics.assessmentmetricdefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_metrics', to='analytics.assessmenttemplate')),
            ],
            options={
                'ordering': ['template', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row_key', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committed', 'Committed')], default='draft', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_assessments', to='analytics.assessmentevent')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_assessments', to='analytics.assessmentimportbatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='players.player')),
                ('roster_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_records', to='seasons.playerrostermembership')),
            ],
            options={
                'ordering': ['event', 'player__last_name', 'player__first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating_scale_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating_scale_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('choice_value', models.CharField(blank=True, max_length=160)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_value', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_column', models.CharField(blank=True, max_length=20)),
                ('source_header', models.CharField(blank=True, max_length=160)),
                ('source_kind', models.CharField(choices=[('imported', 'Imported'), ('manual', 'Manual'), ('manual_corrected', 'Manual Correction')], default='imported', max_length=40)),
                ('is_imported', models.BooleanField(default=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_values', to='analytics.assessmentimportrow')),
                ('player_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='analytics.playerassessment')),
                ('template_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_values', to='analytics.assessmenttemplatemetric')),
            ],
            options={
                'ordering': ['template_metric__display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmenttemplate',
            index=models.Index(fields=['key', 'version'], name='analytics_a_key_eb15b4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmenttemplate',
            index=models.Index(fields=['is_active', 'key'], name='analytics_a_is_acti_90eff4_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttemplate',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='analytics_unique_assessment_template_version'),
        ),
        migrations.AddIndex(
            model_name='assessmentscoringprofile',
            index=models.Index(fields=['key', 'version'], name='analytics_a_key_f400cd_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentscoringprofile',
            index=models.Index(fields=['is_active', 'key'], name='analytics_a_is_acti_8f1a48_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscoringprofile',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='analytics_unique_assessment_scoring_profile_version'),
        ),
        migrations.AddIndex(
            model_name='assessmentmetricdefinition',
            index=models.Index(fields=['is_active', 'key'], name='analytics_a_is_acti_af8128_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentimporttemplate',
            index=models.Index(fields=['key', 'version'], name='analytics_a_key_db23b6_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentimporttemplate',
            index=models.Index(fields=['is_active', 'key'], name='analytics_a_is_acti_7920fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentimporttemplate',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='analytics_unique_assessment_import_template_version'),
        ),
        migrations.AddField(
            model_name='assessmentimportrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='analytics.assessmentimportbatch'),
        ),
        migrations.AddField(
            model_name='assessmentimportrow',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_import_rows', to='players.player'),
        ),
        migrations.AddField(
            model_name='assessmentimportrow',
            name='roster_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_import_rows', to='seasons.playerrostermembership'),
        ),
        migrations.AddField(
            model_name='assessmentimportbatch',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='analytics.assessmentevent'),
        ),
        migrations.AddField(
            model_name='assessmentimportbatch',
            name='import_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='analytics.assessmentimporttemplate'),
        ),
        migrations.AddField(
            model_name='assessmentimportbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='scoring_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='analytics.assessmentscoringprofile'),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_events', to='seasons.season'),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='analytics.assessmenttemplate'),
        ),
        migrations.AddIndex(
            model_name='playerassessment',
            index=models.Index(fields=['player', 'event'], name='analytics_p_player__dfe03f_idx'),
        ),
        migrations.AddIndex(
            model_name='playerassessment',
            index=models.Index(fields=['event', 'status'], name='analytics_p_event_i_3f6c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='playerassessment',
            index=models.Index(fields=['import_batch'], name='analytics_p_import__32b6cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerassessment',
            constraint=models.UniqueConstraint(fields=('player', 'event'), name='analytics_unique_player_assessment_per_event'),
        ),
        migrations.AddIndex(
            model_name='assessmentvalue',
            index=models.Index(fields=['player_assessment', 'template_metric'], name='analytics_a_player__06f8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentvalue',
            index=models.Index(fields=['template_metric', 'numeric_value'], name='analytics_a_templat_f67ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentvalue',
            index=models.Index(fields=['source_sheet', 'source_row'], name='analytics_a_source__1a2c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentvalue',
            index=models.Index(fields=['is_manual_override'], name='analytics_a_is_manu_d09571_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentvalue',
            constraint=models.UniqueConstraint(fields=('player_assessment', 'template_metric'), name='analytics_unique_assessment_value_per_metric'),
        ),
        migrations.AddIndex(
            model_name='assessmenttemplatemetric',
            index=models.Index(fields=['template', 'display_order'], name='analytics_a_templat_906453_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmenttemplatemetric',
            index=models.Index(fields=['category', 'display_order'], name='analytics_a_categor_152f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmenttemplatemetric',
            index=models.Index(fields=['metric', 'template'], name='analytics_a_metric__78ceed_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttemplatemetric',
            constraint=models.UniqueConstraint(fields=('template', 'metric'), name='analytics_unique_metric_per_assessment_template'),
        ),
        migrations.AddIndex(
            model_name='assessmentimportrow',
            index=models.Index(fields=['batch', 'status'], name='analytics_a_batch_i_74ae38_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentimportrow',
            index=models.Index(fields=['player', 'batch'], name='analytics_a_player__a7a96e_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentimportrow',
            index=models.Index(fields=['source_sheet', 'source_row'], name='analytics_a_source__c0e066_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_key'), name='analytics_unique_assessment_import_row_key'),
        ),
        migrations.AddIndex(
            model_name='assessmentimportbatch',
            index=models.Index(fields=['event', 'status'], name='analytics_a_event_i_76debe_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentimportbatch',
            index=models.Index(fields=['workbook_sha256'], name='analytics_a_workboo_1a357e_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentimportbatch',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='analytics_a_uploade_884708_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentevent',
            index=models.Index(fields=['season', 'is_active'], name='analytics_a_season__b0de99_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentevent',
            index=models.Index(fields=['division', 'is_active'], name='analytics_a_divisio_a3dd83_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentevent',
            index=models.Index(fields=['slug'], name='analytics_a_slug_38de60_idx'),
        ),
    ]
