# Generated by Django 4.2.30 on 2026-07-31 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("players", "0003_playerimportbatch_season_and_more"),
        ("analytics", "0006_assessmentevent_assessmentimportbatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentimportbatch",
            name="acknowledgement_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assessmentimportbatch",
            name="config_checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assessmentimportbatch",
            name="preview_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="assessmentimportbatch",
            name="required_warning_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assessmentimportbatch",
            name="validation_errors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assessmentimportbatch",
            name="validation_warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assessmentimportbatch",
            name="warnings_acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentimportbatch",
            name="warnings_acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_assessment_import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessmentimportrow",
            name="conflict_status",
            field=models.CharField(
                choices=[
                    ("none", "No conflict"),
                    ("unresolved", "Unresolved"),
                    ("resolved", "Resolved"),
                ],
                default="none",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="assessmentimportrow",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("matched", "Matched"),
                    ("unmatched", "Unmatched"),
                    ("ambiguous", "Ambiguous"),
                ],
                default="unmatched",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="assessmentimportrow",
            name="metric_changes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assessmentimportrow",
            name="validation_status",
            field=models.CharField(
                choices=[("valid", "Valid"), ("invalid", "Invalid")],
                default="valid",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="assessmentimportrow",
            name="warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assessmentimporttemplate",
            name="assessment_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_templates",
                to="analytics.assessmenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="assessmentscoringprofile",
            name="assessment_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scoring_profiles",
                to="analytics.assessmenttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentvalue",
            name="import_row",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment_values",
                to="analytics.assessmentimportrow",
            ),
        ),
        migrations.AlterField(
            model_name="playerassessment",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="player_assessments",
                to="analytics.assessmentimportbatch",
            ),
        ),
        migrations.AlterField(
            model_name="playerassessment",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment_records",
                to="players.player",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentValueCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("previous_snapshot", models.JSONField(default=dict)),
                ("new_snapshot", models.JSONField(default=dict)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_value_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assessment_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="analytics.assessmentvalue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["assessment_value", "-created_at"],
                        name="analytics_a_assessm_24e7ed_idx",
                    )
                ],
            },
        ),
    ]
