# Generated by Django 4.2.25 on 2026-07-16 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_playerimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSeasonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_role', models.CharField(choices=[('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach'), ('manager', 'Manager'), ('coordinator', 'Coordinator'), ('evaluator', 'Evaluator')], max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('source_identifier', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['season_team__season__name', 'user__username', 'assignment_role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRosterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('guest', 'Guest'), ('removed', 'Removed')], default='active', max_length=40)),
                ('jersey_number', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('source_identifier', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['season_team__season__name', 'player__last_name', 'player__first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-starts_on', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeasonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('division', models.CharField(max_length=80)),
                ('normalized_name', models.CharField(editable=False, max_length=120)),
                ('normalized_division', models.CharField(editable=False, max_length=80)),
                ('external_source', models.CharField(blank=True, max_length=80)),
                ('external_identifier', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='seasons.season')),
            ],
            options={
                'ordering': ['season__name', 'normalized_division', 'normalized_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['key'], name='seasons_sea_key_19cf1b_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['is_active', 'starts_on'], name='seasons_sea_is_acti_4d2b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['is_current'], name='seasons_sea_is_curr_fa354e_idx'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='seasons_unique_current_season'),
        ),
        migrations.AddField(
            model_name='playerrostermembership',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_memberships', to='players.playerimportbatch'),
        ),
        migrations.AddField(
            model_name='playerrostermembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_memberships', to='players.player'),
        ),
        migrations.AddField(
            model_name='playerrostermembership',
            name='season_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_memberships', to='seasons.seasonteam'),
        ),
        migrations.AddField(
            model_name='coachseasonassignment',
            name='season_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coach_assignments', to='seasons.seasonteam'),
        ),
        migrations.AddField(
            model_name='coachseasonassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seasonteam',
            index=models.Index(fields=['season', 'normalized_division', 'normalized_name'], name='seasons_sea_season__255742_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonteam',
            index=models.Index(fields=['season', 'division'], name='seasons_sea_season__ebc575_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonteam',
            index=models.Index(fields=['season', 'is_active'], name='seasons_sea_season__faa9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonteam',
            index=models.Index(fields=['external_source', 'external_identifier'], name='seasons_sea_externa_d9520f_idx'),
        ),
        migrations.AddConstraint(
            model_name='seasonteam',
            constraint=models.UniqueConstraint(fields=('season', 'normalized_division', 'normalized_name'), name='seasons_unique_team_per_season_division'),
        ),
        migrations.AddConstraint(
            model_name='seasonteam',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_source', ''), _negated=True), models.Q(('external_identifier', ''), _negated=True)), fields=('season', 'external_source', 'external_identifier'), name='seasons_unique_team_external_identifier'),
        ),
        migrations.AddIndex(
            model_name='playerrostermembership',
            index=models.Index(fields=['player', 'is_active'], name='seasons_pla_player__612c11_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrostermembership',
            index=models.Index(fields=['season_team', 'is_active'], name='seasons_pla_season__528f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrostermembership',
            index=models.Index(fields=['player', 'is_primary', 'is_active'], name='seasons_pla_player__a38126_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrostermembership',
            index=models.Index(fields=['starts_on', 'ends_on'], name='seasons_pla_starts__1e6e88_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrostermembership',
            index=models.Index(fields=['source', 'source_identifier'], name='seasons_pla_source_31c641_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrostermembership',
            index=models.Index(fields=['import_batch'], name='seasons_pla_import__f10afb_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerrostermembership',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source', ''), _negated=True), models.Q(('source_identifier', ''), _negated=True)), fields=('player', 'season_team', 'source', 'source_identifier'), name='seasons_unique_player_membership_source'),
        ),
        migrations.AddIndex(
            model_name='coachseasonassignment',
            index=models.Index(fields=['user', 'is_active'], name='seasons_coa_user_id_e9754f_idx'),
        ),
        migrations.AddIndex(
            model_name='coachseasonassignment',
            index=models.Index(fields=['season_team', 'is_active'], name='seasons_coa_season__110fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='coachseasonassignment',
            index=models.Index(fields=['user', 'is_primary', 'is_active'], name='seasons_coa_user_id_52b4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='coachseasonassignment',
            index=models.Index(fields=['assignment_role', 'is_active'], name='seasons_coa_assignm_f413bf_idx'),
        ),
        migrations.AddIndex(
            model_name='coachseasonassignment',
            index=models.Index(fields=['source', 'source_identifier'], name='seasons_coa_source_c3a514_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachseasonassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'season_team', 'assignment_role'), name='seasons_unique_active_coach_assignment'),
        ),
    ]
