# Generated by Django 4.2.25 on 2026-07-06 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_playerimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('coach', 'Coach'), ('player', 'Player'), ('parent', 'Parent'), ('guest_evaluator', 'Guest Evaluator')], default='guest_evaluator', max_length=40)),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_from_import', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_profiles', to='players.playerimportbatch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'id'],
                'indexes': [models.Index(fields=['role'], name='accounts_ac_role_4b0b72_idx'), models.Index(fields=['created_from_import'], name='accounts_ac_created_1f52ee_idx'), models.Index(fields=['must_change_password'], name='accounts_ac_must_ch_f84c70_idx')],
            },
        ),
    ]
