# Generated by Django 4.2.25 on 2026-07-06 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('coach', 'Coach'), ('staff', 'Staff')], max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_from_import', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_player_links', to='players.playerimportbatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='players.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'relationship', 'player__last_name', 'player__first_name', 'id'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_45f07b_idx'), models.Index(fields=['player', 'is_active'], name='accounts_us_player__7e6aca_idx'), models.Index(fields=['relationship', 'is_active'], name='accounts_us_relatio_3e1be0_idx'), models.Index(fields=['created_from_import'], name='accounts_us_created_12e3fc_idx'), models.Index(fields=['import_batch'], name='accounts_us_import__cfa23f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userplayerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'player', 'relationship'), name='accounts_unique_active_user_player_relationship'),
        ),
        migrations.AddConstraint(
            model_name='userplayerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True), ('relationship', 'self')), fields=('user',), name='accounts_unique_primary_self_link_per_user'),
        ),
        migrations.AddConstraint(
            model_name='userplayerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True), ('relationship', 'self')), fields=('player',), name='accounts_unique_primary_self_link_per_player'),
        ),
    ]
