# Generated by Django 4.2.25 on 2026-04-12 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_date', models.DateField()),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final'), ('postponed', 'Postponed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('verification_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('awaiting_away_verification', 'Awaiting away verification'), ('verified_final', 'Verified final')], default='scheduled', max_length=30)),
                ('inning_label', models.CharField(blank=True, max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-game_date', '-scheduled_start_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_seasons', to='leaguehub.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_seasons', to='pdp.season')),
            ],
            options={
                'ordering': ['-season__year', 'league__name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('league_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leaguehub.leagueseason')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('story', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_stories', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='leaguehub.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stories', to='leaguehub.team')),
            ],
            options={
                'ordering': ['game__game_date', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='GameScoreAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final'), ('postponed', 'Postponed'), ('canceled', 'Canceled')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final'), ('postponed', 'Postponed'), ('canceled', 'Canceled')], max_length=20)),
                ('previous_verification_status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('awaiting_away_verification', 'Awaiting away verification'), ('verified_final', 'Verified final')], max_length=30)),
                ('new_verification_status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('awaiting_away_verification', 'Awaiting away verification'), ('verified_final', 'Verified final')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('requires_reverification', models.BooleanField(default=False)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_score_audits', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_audit_entries', to='leaguehub.game')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GamePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='leaguehub/game_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='leaguehub.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_photos', to='leaguehub.team')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['game__game_date', 'team__name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='leaguehub.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='leaguehub.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='league_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='leaguehub.leagueseason'),
        ),
        migrations.AddField(
            model_name='game',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamCoachAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('head_coach', 'Head coach'), ('assistant_coach', 'Assistant coach')], default='head_coach', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='leaguehub.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team__name', 'role', 'user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['team', 'role', 'is_active'], name='leaguehub_t_team_id_c32603_idx'), models.Index(fields=['user', 'is_active'], name='leaguehub_t_user_id_0c832c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='teamcoachassignment',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='leaguehub_unique_coach_assignment'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['league_season', 'name'], name='leaguehub_t_league__91da3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('league_season', 'name'), name='leaguehub_unique_team_name_per_season'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('league_season', 'slug'), name='leaguehub_unique_team_slug_per_season'),
        ),
        migrations.AddIndex(
            model_name='leagueseason',
            index=models.Index(fields=['league', 'season'], name='leaguehub_l_league__c7f98f_idx'),
        ),
        migrations.AddConstraint(
            model_name='leagueseason',
            constraint=models.UniqueConstraint(fields=('league', 'season'), name='leaguehub_unique_league_season'),
        ),
        migrations.AddIndex(
            model_name='gamestory',
            index=models.Index(fields=['game', 'team'], name='leaguehub_g_game_id_f2b9a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamestory',
            constraint=models.UniqueConstraint(fields=('game', 'team'), name='leaguehub_unique_story_per_team_per_game'),
        ),
        migrations.AddIndex(
            model_name='gamescoreauditentry',
            index=models.Index(fields=['game', '-created_at'], name='leaguehub_g_game_id_c06e27_idx'),
        ),
        migrations.AddIndex(
            model_name='gamescoreauditentry',
            index=models.Index(fields=['edited_by', '-created_at'], name='leaguehub_g_edited__46001d_idx'),
        ),
        migrations.AddIndex(
            model_name='gamephoto',
            index=models.Index(fields=['game', 'team'], name='leaguehub_g_game_id_35897a_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamephoto',
            constraint=models.UniqueConstraint(fields=('game', 'team'), name='leaguehub_unique_photo_per_team_per_game'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['league_season', 'game_date'], name='leaguehub_g_league__6a5907_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['league_season', 'status', 'game_date'], name='leaguehub_g_league__aba338_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['league_season', 'verification_status', 'game_date'], name='leaguehub_g_league__93b52f_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['league_season', 'is_archived', 'game_date'], name='leaguehub_g_league__9cf8da_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['home_team', 'game_date'], name='leaguehub_g_home_te_171b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['away_team', 'game_date'], name='leaguehub_g_away_te_8f5eae_idx'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('home_team', 'away_team', 'game_date'), name='leaguehub_unique_game_matchup_date'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(('home_team', models.F('away_team')), _negated=True), name='leaguehub_home_away_must_differ'),
        ),
    ]
