# Generated by Django 4.2.25 on 2026-07-01 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('division', models.CharField(blank=True, max_length=80)),
                ('team_name', models.CharField(blank=True, max_length=120)),
                ('school', models.CharField(blank=True, max_length=160)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bats', models.CharField(blank=True, max_length=20)),
                ('throws', models.CharField(blank=True, max_length=20)),
                ('primary_positions', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('players', models.ManyToManyField(blank=True, related_name='tags', to='players.player')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=80)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('original_row', models.JSONField(blank=True, default=dict)),
                ('unmapped_fields', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_player_source_rows', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rows', to='players.player')),
            ],
            options={
                'ordering': ['-imported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSourceIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=80)),
                ('identifier_type', models.CharField(max_length=80)),
                ('identifier_value', models.CharField(max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_identifiers', to='players.player')),
            ],
            options={
                'ordering': ['source', 'identifier_type', 'identifier_value'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=160)),
                ('normalized_alias', models.CharField(editable=False, max_length=160)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('context', models.CharField(blank=True, max_length=160)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='players.player')),
            ],
            options={
                'ordering': ['normalized_alias', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='players_pla_last_na_1786cf_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['division', 'team_name'], name='players_pla_divisio_49c4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_active', 'last_name'], name='players_pla_is_acti_6ed675_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['birthdate'], name='players_pla_birthda_0f2f40_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['birth_year'], name='players_pla_birth_y_75264c_idx'),
        ),
        migrations.AddIndex(
            model_name='playertag',
            index=models.Index(fields=['slug'], name='players_pla_slug_5f78c2_idx'),
        ),
        migrations.AddIndex(
            model_name='playersourcerow',
            index=models.Index(fields=['source', 'source_filename'], name='players_pla_source_3dacfc_idx'),
        ),
        migrations.AddIndex(
            model_name='playersourcerow',
            index=models.Index(fields=['player', 'source'], name='players_pla_player__d2d365_idx'),
        ),
        migrations.AddIndex(
            model_name='playersourcerow',
            index=models.Index(fields=['imported_at'], name='players_pla_importe_7b6da4_idx'),
        ),
        migrations.AddIndex(
            model_name='playersourceidentifier',
            index=models.Index(fields=['source', 'identifier_type'], name='players_pla_source_61b03e_idx'),
        ),
        migrations.AddIndex(
            model_name='playersourceidentifier',
            index=models.Index(fields=['identifier_value'], name='players_pla_identif_2b3568_idx'),
        ),
        migrations.AddConstraint(
            model_name='playersourceidentifier',
            constraint=models.UniqueConstraint(fields=('source', 'identifier_type', 'identifier_value'), name='players_unique_source_identifier'),
        ),
        migrations.AddIndex(
            model_name='playeralias',
            index=models.Index(fields=['normalized_alias'], name='players_pla_normali_e8ddea_idx'),
        ),
        migrations.AddConstraint(
            model_name='playeralias',
            constraint=models.UniqueConstraint(fields=('player', 'normalized_alias'), name='players_unique_alias_per_player'),
        ),
    ]
