# Generated by Django 4.2.25 on 2026-07-02 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=80)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('previewed', 'Previewed'), ('needs_review', 'Needs Review'), ('committed', 'Committed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=40)),
                ('mapping_config', models.JSONField(blank=True, default=dict)),
                ('preview_snapshot', models.JSONField(blank=True, default=dict)),
                ('row_errors', models.JSONField(blank=True, default=list)),
                ('conflict_summary', models.JSONField(blank=True, default=dict)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_conflicted', models.PositiveIntegerField(default=0)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='playerimportbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playersourcerow',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_rows', to='players.playerimportbatch'),
        ),
        migrations.AddIndex(
            model_name='playersourcerow',
            index=models.Index(fields=['import_batch', 'row_number'], name='players_pla_import__f74b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='playerimportbatch',
            index=models.Index(fields=['status', '-created_at'], name='players_pla_status_a91c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='playerimportbatch',
            index=models.Index(fields=['source', '-created_at'], name='players_pla_source_e37ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='playerimportbatch',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='players_pla_uploade_a15127_idx'),
        ),
    ]
