# Generated by Django 4.2.25 on 2026-07-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('players', '0002_playerimportbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerimportbatch',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_import_batches', to='seasons.season'),
        ),
        migrations.AddIndex(
            model_name='playerimportbatch',
            index=models.Index(fields=['season', '-created_at'], name='players_pla_season__4fcae7_idx'),
        ),
    ]
