# Generated by Django 4.2.25 on 2026-03-10 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('division', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'division', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DraftTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='drafts.draft')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('draft', 'name'), ('draft', 'display_order')},
            },
        ),
        migrations.CreateModel(
            name='DraftPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('imported_row', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='drafts.draftteam')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='drafts.draft')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
                'unique_together': {('draft', 'first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='DraftAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('player_imported', 'Player imported'), ('player_drafted', 'Player drafted'), ('draft_pick_reverted', 'Draft pick reverted'), ('player_traded', 'Player traded'), ('player_moved', 'Player moved'), ('player_removed', 'Player removed'), ('team_created', 'Team created'), ('draft_opened', 'Draft opened'), ('draft_closed', 'Draft closed'), ('draft_reopened', 'Draft reopened')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pick_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_reverted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_actions', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='drafts.draft')),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_from', to='drafts.draftteam')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='drafts.draftplayer')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_to', to='drafts.draftteam')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
